export const PASSWORD_CREATE = 'PASSWORD_CREATE';
export const SEED_PHRASE_VIDEO = 'SEED_PHRASE_VIDEO';
export const SEED_PHRASE_REVIEW = 'SEED_PHRASE_REVIEW';
export const SEED_PHRASE_CONFIRM = 'SEED_PHRASE_CONFIRM';
export const ONBOARDING_COMPLETE = 'ONBOARDING_COMPLETE';
